[package]
name = "chip8"
version = "0.1.0"
authors = ["denis <denis@airheadventures.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.34.3"
anyhow = "1.0.34"
getopts = "0.2.21"
rand = "0.6"